import Foundation
import PropertyBased
import Testing

@testable import Hangar

// Postgres's protocol counts bind parameters in a 16-bit field, so one
// statement carries at most 65,535. A multi-row insert binds rows × columns,
// and past the limit PostgresNIO refused with `tooManyParameters` — printing
// the entire statement — so `repo.insert(models)` had an undocumented size
// ceiling. No Swift Postgres library chunks for you; Hangar does now.

@Entity("hangar_generated_only")
struct GeneratedOnly: Sendable, Equatable {
    @ID(generated: true) var id: Int = 0
}

@Suite("Bind-parameter limit")
struct BindLimitUnitTests {
    @Test("a chunk never exceeds the protocol limit, and always holds a row")
    func chunkSizes() async {
        await propertyCheck(count: 500, input: Gen.int(in: 0...70_000)) { columns in
            let rows = Repo.rowsPerInsert(columns: columns)
            #expect(rows >= 1)
            #expect(columns == 0 || rows * columns <= Repo.maximumBindParameters || rows == 1)
            #expect(columns == 0 || (rows + 1) * columns > Repo.maximumBindParameters || rows == Repo.maximumBindParameters)
        }
    }

    @Test("an entity whose every column is generated renders valid inserts")
    func allGenerated() throws {
        #expect(try SQLRenderer.insert(GeneratedOnly()).sql
            == #"INSERT INTO "hangar_generated_only" DEFAULT VALUES RETURNING "id""#)
        #expect(try SQLRenderer.insert([GeneratedOnly(), GeneratedOnly()]).sql
            == #"INSERT INTO "hangar_generated_only" ("id") VALUES (DEFAULT), (DEFAULT) RETURNING "id""#)
    }
}

extension PostgresIntegrationSuite {
    @Suite("Bind-parameter limit (real Postgres)")
    struct BindLimitIntegrationTests {
        static let many = 40_000  // 80,000 binds at two columns a row

        @Test("a batch larger than one statement can bind is inserted whole, in order")
        func largeBatch() async throws {
            try await withRepo { repo in
                let models = (0..<Self.many).map { KV(key: "k\($0)", value: "v\($0)") }
                let stored = try await repo.insert(models)
                #expect(stored.map(\.key) == models.map(\.key))
                #expect(try await repo.count(KV.all) == Self.many)
            }
        }

        @Test("a failure in a late chunk leaves nothing from the early ones")
        func chunksAreAtomic() async throws {
            try await withRepo { repo in
                try await repo.insert(KV(key: "taken", value: "first"))
                var models = (0..<Self.many).map { KV(key: "k\($0)", value: "v") }
                models.append(KV(key: "taken", value: "dup"))
                await #expect {
                    try await repo.insert(models)
                } throws: { ($0 as? DatabaseError)?.isUniqueViolation == true }
                #expect(try await repo.count(KV.all) == 1)
            }
        }

        @Test("inside a transaction the chunks nest as a savepoint")
        func chunksNestInATransaction() async throws {
            try await withRepo { repo in
                try await repo.transaction { tx in
                    try await tx.insert(KV(key: "outer", value: "x"))
                    _ = try await tx.insert((0..<Self.many).map { KV(key: "k\($0)", value: "v") })
                }
                #expect(try await repo.count(KV.all) == Self.many + 1)
            }
        }

        @Test("entities with only generated columns insert, singly and in bulk")
        func generatedOnly() async throws {
            try await withRepo { repo in
                try await repo.execute("DROP TABLE IF EXISTS hangar_generated_only")
                try await repo.execute(
                    "CREATE TABLE hangar_generated_only (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)")
                let one = try await repo.insert(GeneratedOnly())
                let three = try await repo.insert([GeneratedOnly(), GeneratedOnly(), GeneratedOnly()])
                try await repo.execute("DROP TABLE hangar_generated_only")
                #expect(one.id > 0)
                #expect(Set(three.map(\.id)).count == 3)
            }
        }
    }
}
